name: Release Workflow

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  NODE_VERSION: 22.6.0
  PNPM_VERSION: 9.7.1

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Node setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          pnpm-run-install: true

      # Step 3: Configure Git User
      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build Project
        run: pnpm run build

      - name: Clean workspace
        run: |
          rm -rf src dev scripts .vscode
          rm tsconfig.json eslint.config.js .swcrc .prettierrc.json
          rm package.json .gitignore

      - name: Prepare Release Files
        run: |
          # Copy artifacts to release file
          cp -R .github release
          cp -R dist release

          # Delete all root files exept release folder
          find . -mindepth 1 -maxdepth 1 ! -name 'release' -exec rm -rf {} +

           # Copy release files back to the root and clean release folder
          cp -R release/* .
          rm -rf release

          ls

          git add .
          git commit -m "chore(release): prepare release for v${{ github.ref_name }}"

      - name: Push Release Branch
        run: |
          git checkout -b release-${{ github.ref_name }}
          git push origin release-${{ github.ref_name }}

      # - name: Publish Artifacts (Optional)
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: release-artifacts
      #     path: ./dist
