name: Build on Tag Push

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Matches semantic versioning (e.g., v1.0.0)

env:
  NODE_VERSION: 22.6.0
  PNPM_VERSION: 9.7.1
  DO_NOT_TRACK: 1 # Disable Turbopack telemetry
  NEXT_TELEMETRY_DISABLED: 1 # Disable Next telemetry

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Node setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          pnpm-install-cache-key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: pnpm install

      # Step 4: Run the build process
      - name: Build Project
        run: pnpm run build # Replace with your build script

      # Step 6: Verify artifact content (debugging step)
      - name: List remaining files
        run: ls -R . # Debugging step to confirm correct files remain

      # Step 7: Publish artifacts
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist
            package.json
